- hosts: tg_bot
  vars:
    ansible_host_key_checking: false
    ansible_become_pass: "1"
  become: yes
  tasks:

    - name: Установка необходимых пакетов
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Клонирование репозитория
      git:
        repo: https://github.com/kevinisnotkevin/2024.2.git
        dest: /opt/bot

    - name: Установка зависимостей
      command: pip install --break-system-packages -r /opt/bot/requirements.txt

    - name: Копирование .env файла
      copy:
        src: .env
        dest: /opt/bot/.env

    - name: Запуск бота
      shell: nohup python3 /opt/bot/bot.py > /opt/bot/logs.log 2>&1 &
      args:
        chdir: /opt/bot

