- hosts: db
  vars:
    ansible_host_key_checking: false
    ansible_become_pass: "1"
  become: yes
  tasks:

    - name: Установка PostgreSQL
      apt:
        name:
          - postgresql
          - sudo
        state: present

    - name: Конфигурация PostgreSQL
      copy:
        src: config-postgresql
        dest: /etc/postgresql/15/main/postgresql.conf

    - name: Копирование pg_hba.conf
      copy:
        src: pg_hba.conf
        dest: /etc/postgresql/15/main/pg_hba.conf

    - name: Перезапуск PostgreSQL
      systemd:
        name: postgresql
        state: restarted

#    - name: Создание пользователя repl_user
#      shell: "sudo -u postgres psql -c \"CREATE USER repl_user WITH REPLICATION ENCRYPTED PASSWORD '1';\""

#    - name: Создание слота репликации
#      become_user: postgres
#      postgresql_query:
#        query: "SELECT pg_create_physical_replication_slot('replication_slot');"

- hosts: repl_db
  vars:
    ansible_host_key_checking: false
    ansible_become_pass: "1"
  become: yes
  tasks:

    - name: Установка PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Конфигурация PostgreSQL
      copy:
        src: config-postgresql
        dest: /etc/postgresql/15/main/postgresql.conf

    - name: Копирование pg_hba.conf
      copy:
        src: pg_hba.conf
        dest: /etc/postgresql/15/main/pg_hba.conf

    - name: Add postgres user to the sudo group
      user:
        name: postgres
        groups: sudo
        append: yes

    - name: Настройка postgres
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "postgres ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'

    - name: Остановка PostgreSQL
      systemd:
        name: postgresql
        state: stopped

    - name: Удаление файлов из каталога main
      shell: rm -rf /var/lib/postgresql/15/main/*

    - name: Настройка репликации
      become: yes
#      become_user: postgres
      shell: cd /var/lib/postgresql && sudo -u postgres pg_basebackup -R -h 172.16.180.152 -U repl_user -D /var/lib/postgresql/15/main -P

    - name: Запуск PostgreSQL
      systemd:
        name: postgresql
        state: started
